---
abstract: 'Generate Cypher queries in Perl'
author:
  - 'Mark A. Jensen'
build_requires:
  Tie::IxHash: '0'
  Try::Tiny: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Neo4j-Cypher-Abstract
provides:
  Neo4j::Cypher::Abstract:
    file: lib/Neo4j/Cypher/Abstract.pm
    version: '0.1001'
  Neo4j::Cypher::Abstract::Peeler:
    file: lib/Neo4j/Cypher/Abstract/Peeler.pm
    version: '0.1001'
  Neo4j::Cypher::Pattern:
    file: lib/Neo4j/Cypher/Pattern.pm
    version: '0.1001'
requires:
  List::Util: '1.33'
  Scalar::Util: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Neo4j-Cypher-Abstract
  license: http://dev.perl.org/licenses/
  repository: http://github.com/majensen/cypher-abstract.git
version: '0.1001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
